//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employment.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Employment.Domain.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to this Cannot Apply Again Within 24 Hours.
        /// </summary>
        public static string CannotApplyAgainWithin24Hours
        {
            get
            {
                return ResourceManager.GetString("CannotApplyAgainWithin24Hours", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to this email is already exist.
        /// </summary>
        public static string EmailAlreadyInUse {
            get {
                return ResourceManager.GetString("EmailAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty field.
        /// </summary>
        public static string EmptyField {
            get {
                return ResourceManager.GetString("EmptyField", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to empty field.
        /// </summary>
        public static string MaxVacancyApplicationsExceeded
        {
            get
            {
                return ResourceManager.GetString("MaxVacancyApplicationsExceeded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Incorrect current password.
        /// </summary>
        public static string IncorrectCurrentPassword {
            get {
                return ResourceManager.GetString("IncorrectCurrentPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid url.
        /// </summary>
        public static string InvalidUrl
        {
            get
            {
                return ResourceManager.GetString("InvalidUrl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You already set your account extra data.
        /// </summary>
        public static string ExtraDataAlreadyAdded {
            get {
                return ResourceManager.GetString("ExtraDataAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch user data.
        /// </summary>
        public static string FailedToFetchUserData {
            get {
                return ResourceManager.GetString("FailedToFetchUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incorrect data.
        /// </summary>
        public static string IncorrectData {
            get {
                return ResourceManager.GetString("IncorrectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incorrect email or password.
        /// </summary>
        public static string IncorrectEmailOrPassword {
            get {
                return ResourceManager.GetString("IncorrectEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the email format is incorrect.
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid OTP.
        /// </summary>
        public static string InvalidOTP {
            get {
                return ResourceManager.GetString("InvalidOTP", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Max Length Exceeded.
        /// </summary>
        public static string MaxLengthExceeded
        {
            get
            {
                return ResourceManager.GetString("MaxLengthExceeded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid Max Applications.
        /// </summary>
        public static string InvalidMaxApplications
        {
            get
            {
                return ResourceManager.GetString("InvalidMaxApplications", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expiry Date In Future.
        /// </summary>
        public static string ExpiryDateInFuture
        {
            get
            {
                return ResourceManager.GetString("ExpiryDateInFuture", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid Vacancy Status.
        /// </summary>
        public static string InvalidVacancyStatus
        {
            get
            {
                return ResourceManager.GetString("InvalidVacancyStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to not found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string PasswordsNotMatch {
            get {
                return ResourceManager.GetString("PasswordsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this phone is already exist.
        /// </summary>
        public static string PhoneNumberAlreadyUsed {
            get {
                return ResourceManager.GetString("PhoneNumberAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this name is already exist.
        /// </summary>
        public static string RedundantData {
            get {
                return ResourceManager.GetString("RedundantData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully.
        /// </summary>
        public static string SuccessChangePassword {
            get {
                return ResourceManager.GetString("SuccessChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successful operation.
        /// </summary>
        public static string SuccessfulOperation {
            get {
                return ResourceManager.GetString("SuccessfulOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your account has been blocked.
        /// </summary>
        public static string YourAccountHasBeenBlocked {
            get {
                return ResourceManager.GetString("YourAccountHasBeenBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your account has been deactivated.
        /// </summary>
        public static string YourAccountHasBeenDeactivated {
            get {
                return ResourceManager.GetString("YourAccountHasBeenDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your account has been locked out.
        /// </summary>
        public static string YourAccountHasBeenLockedOut {
            get {
                return ResourceManager.GetString("YourAccountHasBeenLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your email has not been confirmed yet.
        /// </summary>
        public static string YourEmailNotConfirmedYet {
            get {
                return ResourceManager.GetString("YourEmailNotConfirmedYet", resourceCulture);
            }
        }
    }
}
